### ISSUE TITLE
how to compile/run (java)

### ISSUE THREAD

**Issue by mo8Zomo0** [hardillb/TRADFRI2MQTT#11]
Hi!

I noticed the snapshots are a bit older present here, how to compile or run the current code,
what are dependencies which need to be in place upfront?
Just a short info on what is required to get it to run might be handy. Thx!

**Comment by hardillb** [comment]
- Clone the repo
- run `mvn install` in the root directory
- The packaged jar file will end up under the target directory

**Comment by mo8Zomo0** [comment]
things can be so simple, I had installed the local packages for maven yesterday, that seem to have worked. Files compiled., thx case can be closed.

Maybe worth mentioning that in the readme.
