### ISSUE TITLE
docker on rapsberry pi

### ISSUE THREAD

**Issue by mo8Zomo0** [hardillb/TRADFRI2MQTT#12]
Hi!

I tried to run the docker part on a raspberry pi. Sadly I did not succeed. 
The version (1.5) which comes with Raspbian8 seems to be to old to work (like no mavin).
I then tried some other version 1.11.1-1 installed it but fails:

# docker build -t tradfri2mqtt .
Sending build context to Docker daemon 1.787 MB
Step 1 : FROM maven:onbuild-alpine
# Executing 2 build triggers...
Step 1 : ADD . /usr/src/app
 ---> Using cache
Step 1 : RUN mvn install
 ---> Running in 534aced54827
rpc error: code = 2 desc = "oci runtime error: exec format error"

**Comment by hardillb** [comment]
You will need to change the FROM value at the top of the Dockerfile to a image that will run on a Raspberry Pi, I do not believe the alpine builds will work on ARM

**Comment by mo8Zomo0** [comment]
ok, thats most likely the case, thank you for your quick answer! I will try the non docker way for now, thx!

**Comment by AnderssonPeter** [comment]
https://hub.docker.com/r/arm32v6/alpine/ should work on a raspberry pi.

**Comment by mo8Zomo0** [comment]
@AnderssonPeter Thank you, might be interesting to try! Used it without docker, but might be worth a try!

**Comment by hardillb** [comment]
@AnderssonPeter If you actually look at the Dockerfile you will see that it's importing  `maven:onbuild-alpine` so it's not just a need to find a alpine build that runs on Arm, it's the need to find a full maven stack packaged for Arm
