### ISSUE TITLE
MQTT broker password and usernames

### ISSUE THREAD

**Issue by genestealer** [hardillb/TRADFRI2MQTT#7]
Can you support mosquitto brokers with usernames and passwords?

**Comment by hardillb** [comment]
I'm sure that wouldn't be that hard, feel free to submit a pull request with changes for consideration

**Comment by genestealer** [comment]
I think it's a little beyond me I'm afraid.

**Comment by hardillb** [comment]
That's a shame because it really would be very easy

**Comment by baahver** [comment]
Hello hardillb, Or maybe other developers,
My mosquitto/mqtt  broker is set up with username and password. 
I do understand that if someone is a developer and understand coding in python (or is this java?), it wouldn't be that hard to implement this username and password. I'm not a developer too. Not at all. But I like to experiment with code. But in this case this did not help me at all. 
I tried some code, but that seemed to be python. My mistake.
Now I found this example: 
[On stackoverflow](https://stackoverflow.com/questions/51626898/how-can-i-connect-a-java-mqtt-client-with-username-and-password-to-an-emqttdemq)
It would be great if someone could help me with this code, and implement this! 
(I create a docker instance, and try to run it as docker container)

**Comment by hardillb** [comment]
As I said before, submit a PR and I'll look at it, but I've not really touched this code (which was purely intended as a tool to explore Ikea's interface) in 5 years.

You've found an example that clearly shows what needs changing, so take that and apply it this code and learn a little while your at it, but I have no interest in doing it for you.
